//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddOrUpdateUser", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class AddOrUpdateUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int accountStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateTimeCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int subscriptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userRoleForUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userSubscriptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int accountState {
            get {
                return this.accountStateField;
            }
            set {
                if ((this.accountStateField.Equals(value) != true)) {
                    this.accountStateField = value;
                    this.RaisePropertyChanged("accountState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateTimeCreated {
            get {
                return this.dateTimeCreatedField;
            }
            set {
                if ((this.dateTimeCreatedField.Equals(value) != true)) {
                    this.dateTimeCreatedField = value;
                    this.RaisePropertyChanged("dateTimeCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int subscriptionType {
            get {
                return this.subscriptionTypeField;
            }
            set {
                if ((this.subscriptionTypeField.Equals(value) != true)) {
                    this.subscriptionTypeField = value;
                    this.RaisePropertyChanged("subscriptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userRoleForUser {
            get {
                return this.userRoleForUserField;
            }
            set {
                if ((object.ReferenceEquals(this.userRoleForUserField, value) != true)) {
                    this.userRoleForUserField = value;
                    this.RaisePropertyChanged("userRoleForUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userSubscriptionType {
            get {
                return this.userSubscriptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.userSubscriptionTypeField, value) != true)) {
                    this.userSubscriptionTypeField = value;
                    this.RaisePropertyChanged("userSubscriptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userType {
            get {
                return this.userTypeField;
            }
            set {
                if ((this.userTypeField.Equals(value) != true)) {
                    this.userTypeField = value;
                    this.RaisePropertyChanged("userType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetHouseDetails", Namespace="http://schemas.datacontract.org/2004/07/TipezeNyumbaService.ModelsWrapperObjects")]
    [System.SerializableAttribute()]
    public partial class GetHouseDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bedroomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateHouseWillBeAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateUploadedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string districtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fenceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int houseIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string houseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool masterBedroomEnsuiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeOfPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numberOfGaragesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumber2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool selfContainedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string whatsAppContactNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bedrooms {
            get {
                return this.bedroomsField;
            }
            set {
                if ((this.bedroomsField.Equals(value) != true)) {
                    this.bedroomsField = value;
                    this.RaisePropertyChanged("bedrooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateHouseWillBeAvailable {
            get {
                return this.dateHouseWillBeAvailableField;
            }
            set {
                if ((this.dateHouseWillBeAvailableField.Equals(value) != true)) {
                    this.dateHouseWillBeAvailableField = value;
                    this.RaisePropertyChanged("dateHouseWillBeAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateUploaded {
            get {
                return this.dateUploadedField;
            }
            set {
                if ((this.dateUploadedField.Equals(value) != true)) {
                    this.dateUploadedField = value;
                    this.RaisePropertyChanged("dateUploaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string district {
            get {
                return this.districtField;
            }
            set {
                if ((object.ReferenceEquals(this.districtField, value) != true)) {
                    this.districtField = value;
                    this.RaisePropertyChanged("district");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fenceType {
            get {
                return this.fenceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.fenceTypeField, value) != true)) {
                    this.fenceTypeField = value;
                    this.RaisePropertyChanged("fenceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int houseID {
            get {
                return this.houseIDField;
            }
            set {
                if ((this.houseIDField.Equals(value) != true)) {
                    this.houseIDField = value;
                    this.RaisePropertyChanged("houseID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string houseState {
            get {
                return this.houseStateField;
            }
            set {
                if ((object.ReferenceEquals(this.houseStateField, value) != true)) {
                    this.houseStateField = value;
                    this.RaisePropertyChanged("houseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool masterBedroomEnsuite {
            get {
                return this.masterBedroomEnsuiteField;
            }
            set {
                if ((this.masterBedroomEnsuiteField.Equals(value) != true)) {
                    this.masterBedroomEnsuiteField = value;
                    this.RaisePropertyChanged("masterBedroomEnsuite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modeOfPayment {
            get {
                return this.modeOfPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.modeOfPaymentField, value) != true)) {
                    this.modeOfPaymentField = value;
                    this.RaisePropertyChanged("modeOfPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numberOfGarages {
            get {
                return this.numberOfGaragesField;
            }
            set {
                if ((this.numberOfGaragesField.Equals(value) != true)) {
                    this.numberOfGaragesField = value;
                    this.RaisePropertyChanged("numberOfGarages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber1 {
            get {
                return this.phoneNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumber1Field, value) != true)) {
                    this.phoneNumber1Field = value;
                    this.RaisePropertyChanged("phoneNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber2 {
            get {
                return this.phoneNumber2Field;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumber2Field, value) != true)) {
                    this.phoneNumber2Field = value;
                    this.RaisePropertyChanged("phoneNumber2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool selfContained {
            get {
                return this.selfContainedField;
            }
            set {
                if ((this.selfContainedField.Equals(value) != true)) {
                    this.selfContainedField = value;
                    this.RaisePropertyChanged("selfContained");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string whatsAppContactNumber {
            get {
                return this.whatsAppContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.whatsAppContactNumberField, value) != true)) {
                    this.whatsAppContactNumberField = value;
                    this.RaisePropertyChanged("whatsAppContactNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TipezeNyumbaClientService.ITipezeNyumbaService")]
    public interface ITipezeNyumbaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/getMessage", ReplyAction="http://tempuri.org/ITipezeNyumbaService/getMessageResponse")]
        string getMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/getMessage", ReplyAction="http://tempuri.org/ITipezeNyumbaService/getMessageResponse")]
        System.Threading.Tasks.Task<string> getMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/getUser", ReplyAction="http://tempuri.org/ITipezeNyumbaService/getUserResponse")]
        TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser[] getUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/getUser", ReplyAction="http://tempuri.org/ITipezeNyumbaService/getUserResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser[]> getUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/AddANewUser", ReplyAction="http://tempuri.org/ITipezeNyumbaService/AddANewUserResponse")]
        bool AddANewUser(TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/AddANewUser", ReplyAction="http://tempuri.org/ITipezeNyumbaService/AddANewUserResponse")]
        System.Threading.Tasks.Task<bool> AddANewUserAsync(TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserProfile", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserProfileResponse")]
        TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser GetUserProfile(int userID, string userToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetUserProfile", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetUserProfileResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser> GetUserProfileAsync(int userID, string userToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAuntheticationToken", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAuntheticationTokenResponse")]
        string GetAuntheticationToken(string phoneNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAuntheticationToken", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAuntheticationTokenResponse")]
        System.Threading.Tasks.Task<string> GetAuntheticationTokenAsync(string phoneNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDistrict", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDistrictResponse")]
        TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[] GetAllHousesByDistrict(string district);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDistrict", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDistrictResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[]> GetAllHousesByDistrictAsync(string district);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateHouseAvailable", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateHouseAvailableResponse")]
        TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[] GetAllHousesByDateHouseAvailable(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateHouseAvailable", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateHouseAvailableResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[]> GetAllHousesByDateHouseAvailableAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateRange", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateRangeResponse")]
        TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[] GetAllHousesByDateRange(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateRange", ReplyAction="http://tempuri.org/ITipezeNyumbaService/GetAllHousesByDateRangeResponse")]
        System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[]> GetAllHousesByDateRangeAsync(System.DateTime startDate, System.DateTime endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITipezeNyumbaServiceChannel : TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.ITipezeNyumbaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipezeNyumbaServiceClient : System.ServiceModel.ClientBase<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.ITipezeNyumbaService>, TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.ITipezeNyumbaService {
        
        public TipezeNyumbaServiceClient() {
        }
        
        public TipezeNyumbaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipezeNyumbaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipezeNyumbaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipezeNyumbaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getMessage() {
            return base.Channel.getMessage();
        }
        
        public System.Threading.Tasks.Task<string> getMessageAsync() {
            return base.Channel.getMessageAsync();
        }
        
        public TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser[] getUser() {
            return base.Channel.getUser();
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser[]> getUserAsync() {
            return base.Channel.getUserAsync();
        }
        
        public bool AddANewUser(TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser newUser) {
            return base.Channel.AddANewUser(newUser);
        }
        
        public System.Threading.Tasks.Task<bool> AddANewUserAsync(TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser newUser) {
            return base.Channel.AddANewUserAsync(newUser);
        }
        
        public TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser GetUserProfile(int userID, string userToken) {
            return base.Channel.GetUserProfile(userID, userToken);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.AddOrUpdateUser> GetUserProfileAsync(int userID, string userToken) {
            return base.Channel.GetUserProfileAsync(userID, userToken);
        }
        
        public string GetAuntheticationToken(string phoneNumber, string password) {
            return base.Channel.GetAuntheticationToken(phoneNumber, password);
        }
        
        public System.Threading.Tasks.Task<string> GetAuntheticationTokenAsync(string phoneNumber, string password) {
            return base.Channel.GetAuntheticationTokenAsync(phoneNumber, password);
        }
        
        public TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[] GetAllHousesByDistrict(string district) {
            return base.Channel.GetAllHousesByDistrict(district);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[]> GetAllHousesByDistrictAsync(string district) {
            return base.Channel.GetAllHousesByDistrictAsync(district);
        }
        
        public TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[] GetAllHousesByDateHouseAvailable(System.DateTime date) {
            return base.Channel.GetAllHousesByDateHouseAvailable(date);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[]> GetAllHousesByDateHouseAvailableAsync(System.DateTime date) {
            return base.Channel.GetAllHousesByDateHouseAvailableAsync(date);
        }
        
        public TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[] GetAllHousesByDateRange(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetAllHousesByDateRange(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<TipezeNyumbaConsoleAppClient.TipezeNyumbaClientService.GetHouseDetails[]> GetAllHousesByDateRangeAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetAllHousesByDateRangeAsync(startDate, endDate);
        }
    }
}
