//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipezeNyumbaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.HouseBookings = new HashSet<HouseBooking>();
            this.HouseFavourites = new HashSet<HouseFavourite>();
            this.HouseOwners = new HashSet<HouseOwner>();
            this.HouseUrls = new HashSet<HouseUrl>();
            this.InterestedClients = new HashSet<InterestedClient>();
        }
    
        public int houseID { get; set; }
        public int districtHouseIsLocated { get; set; }
        public int locationWithInDistrict { get; set; }
        public int bedrooms { get; set; }
        public bool masterBedroomEnsuite { get; set; }
        public bool selfContained { get; set; }
        public Nullable<int> numberOfGarages { get; set; }
        public int fenceType { get; set; }
        public System.DateTime dateHouseWillBeAvailable { get; set; }
        public decimal price { get; set; }
        public int modeOfPayment { get; set; }
        public System.DateTime dateUploaded { get; set; }
        public string description { get; set; }
        public int currentHouseState { get; set; }
        public int state { get; set; }
    
        public virtual District District { get; set; }
        public virtual FenceType FenceType1 { get; set; }
        public virtual FieldState FieldState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseBooking> HouseBookings { get; set; }
        public virtual HouseContactDetail HouseContactDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseFavourite> HouseFavourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseOwner> HouseOwners { get; set; }
        public virtual HouseState HouseState { get; set; }
        public virtual LocationsInDistrict LocationsInDistrict { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HouseUrl> HouseUrls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterestedClient> InterestedClients { get; set; }
    }
}
