//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipezeNyumbaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseBooking
    {
        public int houseBookID { get; set; }
        public int houseID { get; set; }
        public int userID { get; set; }
        public System.DateTime dateOfMeeting { get; set; }
        public System.TimeSpan timeFrom { get; set; }
        public System.TimeSpan timeTo { get; set; }
        public int status { get; set; }
        public System.DateTime dateCreated { get; set; }
    
        public virtual FieldState FieldState { get; set; }
        public virtual House House { get; set; }
        public virtual User User { get; set; }
    }
}
