//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipezeNyumbaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSession
    {
        public int loginSessionID { get; set; }
        public int userID { get; set; }
        public string SessionToken { get; set; }
        public System.DateTime DateAndTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
